"""Fix upifraud.html template with proper HTML structure."""
import os

lines = [
    "{% extends 'base.html' %}",
    "{% block title %}UPI Fraud Detection - CyberShield{% endblock %}",
    "{% block content %}",
    '<section class="py-4" data-aos="fade-up">',
    '  <div class="row g-4">',
    '    <div class="col-lg-4">',
    '      <div class="cyber-card p-4">',
    '        <h3 class="fw-bold mb-3"><i class="fa-solid fa-receipt me-2" style="color:var(--neon)"></i> UPI Fraud Detection</h3>',
    '        <p class="text-muted small mb-4">Enter a UPI ID or upload a UPI QR. Server decodes QR and computes a fraud risk score.</p>',
    "        <form method=\"post\" action=\"{{ url_for('modules.upi_module') }}\" enctype=\"multipart/form-data\">",
    '          <div class="mb-3">',
    '            <label class="form-label">UPI ID (required)</label>',
    "            <input class=\"form-control\" name=\"upi_id\" maxlength=\"120\" placeholder=\"name@bank\" value=\"{{ request.form.get('upi_id','') if request and request.form else '' }}\" />",
    '          </div>',
    '          <div class="mb-3">',
    '            <label class="form-label">Or Upload UPI QR</label>',
    '            <input class="form-control" type="file" name="qr_image" accept="image/*" />',
    '            <div class="form-text text-muted">PNG/JPG.</div>',
    '          </div>',
    '          <div class="mb-3">',
    '            <label class="form-label">Payment link / text (optional)</label>',
    "            <textarea class=\"form-control\" name=\"payment_link\" rows=\"3\" maxlength=\"2000\" placeholder=\"Paste the payment URL or message text here\">{{ request.form.get('payment_link','') if request and request.form else '' }}</textarea>",
    '          </div>',
    '          <div class="d-grid gap-2">',
    '            <button class="btn cyber-btn" type="submit" name="scan" value="1">',
    '              Analyze <i class="fa-solid fa-shield-halved ms-2"></i>',
    '            </button>',
    '          </div>',
    '        </form>',
    '        {% if handle_error %}',
    '          <div class="alert alert-warning mt-3 mb-0" role="alert">{{ handle_error }}</div>',
    '        {% endif %}',
    '      </div>',
    '    </div>',
    '    <div class="col-lg-8">',
    '      <div class="cyber-card p-4 result-card h-100">',
    '        <h4 class="fw-bold mb-3">Result</h4>',
    '        {% if cyber_report_success %}',
    '          <div class="alert alert-success mb-3" role="alert">',
    '            <i class="fa-solid fa-check-circle me-2"></i> {{ cyber_report_success }}',
    '          </div>',
    '        {% endif %}',
    '        {% if scan %}',
    '          <div class="mb-3 p-3 rounded-3 border',
    "            {% if scan.status == 'High Risk' %}bg-danger bg-opacity-10 border-danger border-opacity-25",
    "            {% elif scan.status == 'Medium Risk' %}bg-warning bg-opacity-10 border-warning border-opacity-25",
    "            {% else %}bg-success bg-opacity-10 border-success border-opacity-25{% endif %}\">",
    '            <div class="d-flex align-items-center gap-3">',
    '              <div class="fs-2">',
    "                {% if scan.status == 'High Risk' %}&#128683;",
    "                {% elif scan.status == 'Medium Risk' %}&#9888;&#65039;",
    "                {% else %}&#9989;{% endif %}",
    '              </div>',
    '              <div>',
    '                <div class="fw-bold fs-6',
    "                  {% if scan.status == 'High Risk' %}text-danger",
    "                  {% elif scan.status == 'Medium Risk' %}text-warning",
    "                  {% else %}text-success{% endif %}\">",
    '                  {{ scan.payment_recommendation }}',
    '                </div>',
    '                <div class="text-muted small mt-1">Based on our fraud analysis, this is the recommended action for this UPI ID.</div>',
    '              </div>',
    '            </div>',
    '          </div>',
    '          <div class="d-flex justify-content-between align-items-center mb-2">',
    '            <span class="badge border-1 p-2',
    "              {% if scan.status == 'High Risk' %}badge-danger",
    "              {% elif scan.status == 'Medium Risk' %}badge-warn",
    "              {% else %}badge-safe{% endif %}\">",
    '              {{ scan.status }}',
    '            </span>',
    '            <span class="text-muted small">Risk Score: <span class="text-white fw-bold">{{ scan.risk_score }}</span>/100</span>',
    '          </div>',
    '          <div class="progress mb-3" style="height:18px;">',
    '            {% if scan.risk_score < 35 %}',
    '              <div class="progress-bar" role="progressbar" style="width: {{ scan.risk_score }}%;"></div>',
    '            {% elif scan.risk_score < 75 %}',
    '              <div class="progress-bar" role="progressbar" style="width: {{ scan.risk_score }}%;"></div>',
    '            {% else %}',
    '              <div class="progress-bar" role="progressbar" style="width: {{ scan.risk_score }}%; background: linear-gradient(90deg, #ff4d6d, #4a7dff);"></div>',
    '            {% endif %}',
    '          </div>',
    '          <div class="mb-3">',
    '            <div class="text-muted small mb-1">UPI handle</div>',
    '            <div class="text-white fw-semibold">{{ scan.upi_handle }}</div>',
    '            {% if scan.provider %}',
    '              <div class="text-muted small mt-1">Provider: <span class="text-white">{{ scan.provider }}</span></div>',
    '            {% endif %}',
    '          </div>',
    '          <div class="row g-3 mb-3">',
    '            {% if scan.reasons and scan.reasons|length > 0 %}',
    '              <div class="col-md-6">',
    '                <div class="text-muted small mb-2">Reasons</div>',
    '                <ul class="mb-0 ps-3">',
    '                  {% for r in scan.reasons %}',
    '                    <li class="mb-1">{{ r }}</li>',
    '                  {% endfor %}',
    '                </ul>',
    '              </div>',
    '            {% endif %}',
    '            {% if scan.recommendations and scan.recommendations|length > 0 %}',
    '              <div class="col-md-6">',
    '                <div class="text-muted small mb-2">Safety recommendations</div>',
    '                <ul class="mb-0 ps-3">',
    '                  {% for rec in scan.recommendations %}',
    '                    <li class="mb-1">{{ rec }}</li>',
    '                  {% endfor %}',
    '                </ul>',
    '              </div>',
    '            {% endif %}',
    '          </div>',
    '          <hr class="border-secondary border-opacity-25" />',
    '          <div class="d-flex flex-column flex-md-row justify-content-between align-items-center gap-3 mt-3">',
    '            <div>',
    '              <div class="text-muted small">Previous reports: <span class="text-white fw-semibold">{{ scan.report_count }}</span></div>',
    '              <div class="text-muted small">Last scanned: <span class="text-white fw-semibold">{{ scan.timestamp }}</span></div>',
    '            </div>',
    '            <div class="d-flex gap-2">',
    "              <form method=\"post\" action=\"{{ url_for('modules.upi_module') }}\">",
    '                <input type="hidden" name="upi_id" value="{{ scan.upi_handle }}" />',
    '                <input type="hidden" name="report" value="1" />',
    '                <button class="btn btn-outline-warning btn-sm" type="submit" {% if not scan.upi_handle %}disabled{% endif %}>',
    '                  <i class="fa-solid fa-flag me-1"></i> Report this UPI',
    '                </button>',
    '              </form>',
    "              <form method=\"post\" action=\"{{ url_for('modules.upi_module') }}\">",
    '                <input type="hidden" name="upi_id" value="{{ scan.upi_handle }}" />',
    '                <input type="hidden" name="cyber_report" value="1" />',
    '                <button class="btn btn-outline-danger btn-sm" type="submit" {% if not scan.upi_handle %}disabled{% endif %}>',
    '                  <i class="fa-solid fa-shield-halved me-1"></i> Report to Cyber Team',
    '                </button>',
    '              </form>',
    '            </div>',
    '          </div>',
    '        {% else %}',
    '          <div class="text-muted">Run a scan to see results.</div>',
    '        {% endif %}',
    '      </div>',
    '    </div>',
    '  </div>',
    '</section>',
    '{% endblock %}',
]

content = '\n'.join(lines)
filepath = r'c:\Users\Poeace\Downloads\cyber\app\templates\modules\upifraud.html'
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print(f"Written {len(content)} bytes to {filepath}")
