# Write upifraud.html template
import os

lines = []
lines.append("{% extends 'base.html' %}")
lines.append("{% block title %}UPI Fraud Detection - CyberShield{% endblock %}")
lines.append("{% block content %}")
lines.append('<section class="py-4" data-aos="fade-up">')
lines.append('  <div class="row g-4">')
lines.append('    <div class="col-lg-4">')
lines.append('      <div class="cyber-card p-4">')
lines.append('        <h3 class="fw-bold mb-3"><i class="fa-solid fa-receipt me-2" style="color:var(--neon)"></i> UPI Fraud Detection</h3>')
lines.append('        <p class="text-muted small mb-4">Enter a UPI ID or upload a UPI QR.</p>')
lines.append('        <form method="post" action="{{ url_for(\'modules.upi_module\') }}" enctype="multipart/form-data">')
lines.append('          <div class="mb-3">')
lines.append('            <label class="form-label">UPI ID (required)</label>')
lines.append('            <input class="form-control" name="upi_id" maxlength="120" placeholder="name@bank" value="{{ request.form.get(\'upi_id\',\'\') if request and request.form else \'\' }}" />')
lines.append('          </div>')
lines.append('          <div class="mb-3">')
lines.append('            <label class="form-label">Or Upload UPI QR</label>')
lines.append('            <input class="form-control" type="file" name="qr_image" accept="image/*" />')
lines.append('            <div class="form-text text-muted">PNG/JPG.</div>')
lines.append('          </div>')
lines.append('          <div class="mb-3">')
lines.append('            <label class="form-label">Payment link / text (optional)</label>')
lines.append('            <textarea class="form-control" name="payment_link" rows="3" maxlength="2000" placeholder="Paste the payment URL or message text here">{{ request.form.get(\'payment_link\',\'\') if request and request.form else \'\' }}</textarea>')
lines.append('          </div>')
lines.append('          <div class="d-grid gap-2">')
lines.append('            <button class="btn cyber-btn" type="submit" name="scan" value="1">')
lines.append('              Analyze <i class="fa-solid fa-shield-halved ms-2"></i>')
lines.append('            </button>')
lines.append('          </div>')
lines.append('        </form>')
lines.append('        {% if handle_error %}')
lines.append('          <div class="alert alert-warning mt-3 mb-0" role="alert">{{ handle_error }}</div>')
lines.append('        {% endif %}')
lines.append('      </div>')
lines.append('    </div>')
lines.append('    <div class="col-lg-8">')
lines.append('      <div class="cyber-card p-4 result-card h-100">')
lines.append('        <h4 class="fw-bold mb-3">Result</h4>')
lines.append('        {% if cyber_report_success %}')
lines.append('          <div class="alert alert-success mb-3" role="alert">')
lines.append('            <i class="fa-solid fa-check-circle me-2"></i> {{ cyber_report_success }}')
lines.append('          </div>')
lines.append('        {% endif %}')
lines.append('        {% if scan %}')
lines.append('          <div class="mb-3 p-3 rounded-3 border')
lines.append("            {% if scan.status == 'High Risk' %}bg-danger bg-opacity-10 border-danger border-opacity-25")
lines.append("            {% elif scan.status == 'Medium Risk' %}bg-warning bg-opacity-10 border-warning border-opacity-25")
lines.append("            {% else %}bg-success bg-opacity-10 border-success border-opacity-25{% endif %}\">")
lines.append('            <div class="d-flex align-items-center gap-3">')
lines.append('              <div class="fs-2">')
lines.append("                {% if scan.status == 'High Risk' %}&amp;#128683;")
lines.append("                {% elif scan.status == 'Medium Risk' %}&amp;#9888;&amp;#65039;")
lines.append("                {% else %}&amp;#9989;{% endif %}")
lines.append('              </div>')
lines.append('              <div>')
lines.append('                <div class="fw-bold fs-6')
lines.append("                  {% if scan.status == 'High Risk' %}text-danger")
lines.append("                  {% elif scan.status == 'Medium Risk' %}text-warning")
lines.append("                  {% else %}text-success{% endif %}\">")
lines.append('                  {{ scan.payment_recommendation }}')
lines.append('                </div>')
lines.append('                <div class="text-muted small mt-1">Based on our fraud analysis, this is the recommended action for this UPI ID.</div>')
lines.append('              </div>')
lines.append('            </div>')
lines.append('          </div>')
lines.append('          <div class="d-flex justify-content-between align-items-center mb-2">')
lines.append('            <span class="badge border-1 p-2')
lines.append("              {% if scan.status == 'High Risk' %}badge-danger")
lines.append("              {% elif scan.status == 'Medium Risk' %}badge-warn")
lines.append("              {% else %}badge-safe{% endif %}\">")
lines.append('              {{ scan.status }}')
lines.append('            </span>')
lines.append('            <span class="text-muted small">Risk Score: <span class="text-white fw-bold">{{ scan.risk_score }}</span>/100</span>')
lines.append('          </div>')
lines.append('          <div class="progress mb-3" style="height:18px;">')
lines.append('            {% if scan.risk_score < 35 %}')
lines.append('              <div class="progress-bar" role="progressbar" style="width: {{ scan.risk_score }}%;"></div>')
lines.append('            {% elif scan.risk_score < 75 %}')
lines.append('              <div class="progress-bar" role="progressbar" style="width: {{ scan.risk_score }}%;"></div>')
lines.append('            {% else %}')
lines.append('              <div class="progress-bar" role="progressbar" style="width: {{ scan.risk_score }}%; background: linear-gradient(90deg, #ff4d6d, #4a7dff);"></div>')
lines.append('            {% endif %}')
lines.append('          </div>')
lines.append('          <div class="mb-3">')
lines.append('            <div class="text-muted small mb-1">UPI handle</div>')
lines.append('            <div class="text-white fw-semibold">{{ scan.upi_handle }}</div>')
lines.append('            {% if scan.provider %}')
lines.append('              <div class="text-muted small mt-1">Provider: <span class="text-white">{{ scan.provider }}</span></div>')
lines.append('            {% endif %}')
lines.append('          </div>')
lines.append('          <div class="row g-3 mb-3">')
lines.append('            {% if scan.reasons and scan.reasons|length > 0 %}')
lines.append('              <div class="col-md-6">')
lines.append('                <div class="text-muted small mb-2">Reasons</div>')
lines.append('                <ul class="mb-0 ps-3">')
lines.append('                  {% for r in scan.reasons %}')
lines.append('                    <li class="mb-1">{{ r }}</li>')
lines.append('                  {% endfor %}')
lines.append('                </ul>')
lines.append('              </div>')
lines.append('            {% endif %}')
lines.append('            {% if scan.recommendations and scan.recommendations|length > 0 %}')
lines.append('              <div class="col-md-6">')
lines.append('                <div class="text-muted small mb-2">Safety recommendations</div>')
lines.append('                <ul class="mb-0 ps-3">')
lines.append('                  {% for rec in scan.recommendations %}')
lines.append('                    <li class="mb-1">{{ rec }}</li>')
lines.append('                  {% endfor %}')
lines.append('                </ul>')
lines.append('              </div>')
lines.append('            {% endif %}')
lines.append('          </div>')
lines.append('          <hr class="border-secondary border-opacity-25" />')
lines.append('          <div class="d-flex flex-column flex-md-row justify-content-between align-items-center gap-3 mt-3">')
lines.append('            <div>')
lines.append('              <div class="text-muted small">Previous reports: <span class="text-white fw-semibold">{{ scan.report_count }}</span></div>')
lines.append('              <div class="text-muted small">Last scanned: <span class="text-white fw-semibold">{{ scan.timestamp }}</span></div>')
lines.append('            </div>')
lines.append('            <div class="d-flex gap-2">')
lines.append('              <form method="post" action="{{ url_for(\'modules.upi_module\') }}">')
lines.append('                <input type="hidden" name="upi_id" value="{{ scan.upi_handle }}" />')
lines.append('                <input type="hidden" name="report" value="1" />')
lines.append('                <button class="btn btn-outline-warning btn-sm" type="submit" {% if not scan.upi_handle %}disabled{% endif %}>')
lines.append('                  <i class="fa-solid fa-flag me-1"></i> Report this UPI')
lines.append('                </button>')
lines.append('              </form>')
lines.append('              <form method="post" action="{{ url_for(\'modules.upi_module\') }}">')
lines.append('                <input type="hidden" name="upi_id" value="{{ scan.upi_handle }}" />')
lines.append('                <input type="hidden" name="cyber_report" value="1" />')
lines.append('                <button class="btn btn-outline-danger btn-sm" type="submit" {% if not scan.upi_handle %}disabled{% endif %}>')
lines.append('                  <i class="fa-solid fa-shield-halved me-1"></i> Report to Cyber Team')
lines.append('                </button>')
lines.append('              </form>')
lines.append('            </div>')
lines.append('          </div>')
lines.append('        {% else %}')
lines.append('          <div class="text-muted">Run a scan to see results.</div>')
lines.append('        {% endif %}')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('</section>')
lines.append('{% endblock %}')

content = "\n".join(lines)
filepath = r'c:\Users\Poeace\Downloads\cyber\app\templates\modules\upifraud.html'
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print(f"Written {len(content)} bytes to {filepath}")
</｜｜DSML｜｜tool_calls>
